import {
  View, Text, StyleSheet, ScrollView,
  TouchableOpacity, Share, Alert,
  ActivityIndicator
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useEffect, useState } from 'react';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { useThemeStore } from '../store/useThemeStore';
import { sessionService } from '../services/sessionService';
import { Colors } from '../constants/theme';
import { QAPair, SessionSummary } from '../types';

export default function SessionDetailScreen() {
  const router = useRouter();

  const { sessionId, autoDownload } = useLocalSearchParams<{
    sessionId: string;
    autoDownload?: string;
  }>();

  const { theme } = useThemeStore();
  const isDark = theme === 'dark';
  const c = isDark ? Colors.dark : Colors.light;

  const [loading, setLoading] = useState(true);
  const [session, setSession] = useState<SessionSummary | null>(null);
  const [qaPairs, setQaPairs] = useState<QAPair[]>([]);
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());

  const fetchDetail = async () => {
    try {
      const data = await sessionService.getSessionDetail(sessionId);
      setSession(data.session);
      setQaPairs(data.qa_pairs);
      return data;
    } catch (err: any) {
      Alert.alert('Error', 'Could not load session detail.');
      return null;
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (sessionId) {
      fetchDetail().then((data) => {
        if (data && autoDownload === 'true') {
          setTimeout(() => {
            handleDownload(data.session, data.qa_pairs);
          }, 500);
        }
      });
    }
  }, [sessionId]);

  const toggleExpand = (id: string) => {
    setExpandedIds(prev => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  };

  const handleDownload = async (
    sessionData: SessionSummary | null = session,
    qaData: QAPair[] = qaPairs
  ) => {
    if (!sessionData || qaData.length === 0) return;

    let report = `AI INTERVIEW COACH — SESSION REPORT\n`;
    report += `${'='.repeat(50)}\n\n`;
    report += `Role: ${sessionData.seniority} ${sessionData.target_role}\n`;
    report += `Date: ${new Date(sessionData.created_at).toLocaleDateString('en-IN')}\n`;
    report += `Questions: ${sessionData.total_questions}\n`;
    report += `Average Score: ${sessionData.avg_score?.toFixed(1) || '—'} / 5.0\n\n`;

    qaData.forEach((qa, i) => {
      report += `${'─'.repeat(50)}\n`;
      report += `Q${i + 1}. [${qa.question_type.toUpperCase()}] ${qa.question_text}\n\n`;
      report += `YOUR ANSWER:\n${qa.transcript || 'No answer recorded'}\n\n`;
      report += `SCORE: ${qa.overall_score?.toFixed(1) || '—'} / 5.0\n`;

      if (qa.scores.situation) {
        report += `  S:${qa.scores.situation} T:${qa.scores.task} `;
        report += `A:${qa.scores.action} R:${qa.scores.result} Rel:${qa.scores.relevance}\n`;
      }

      if (qa.strengths) report += `\nSTRENGTHS: ${qa.strengths}\n`;
      if (qa.gaps) report += `GAPS: ${qa.gaps}\n`;
      if (qa.coaching_tip) report += `TIP: ${qa.coaching_tip}\n`;
      if (qa.ideal_answer) report += `\nIDEAL ANSWER:\n${qa.ideal_answer}\n`;

      report += '\n';
    });

    report += `${'='.repeat(50)}\n`;
    report += `Generated by AI Interview Coach\n`;

    try {
      await Share.share({
        message: report,
        title: `Interview Session — ${sessionData.target_role}`,
      });
    } catch (err) {
      Alert.alert('Error', 'Could not share report.');
    }
  };

  const scoreColor = (score: number) =>
    score >= 4 ? '#2ECC9A' :
    score >= 3 ? Colors.terra.DEFAULT :
    Colors.indigo.light;

  const typeIcon = (type: string) =>
    type === 'technical' ? 'code-slash-outline' :
    type === 'situational' ? 'git-branch-outline' :
    'chatbubble-outline';

  if (loading) {
    return (
      <SafeAreaView style={[styles.container, { backgroundColor: c.bg }]}>
        <View style={styles.centered}>
          <ActivityIndicator color={Colors.indigo.DEFAULT} size="large" />
          <Text style={[styles.loadingText, { color: c.text2 }]}>
            Loading session...
          </Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: c.bg }]}>
      <View style={[styles.header, { borderBottomColor: c.border }]}>
        <TouchableOpacity
          onPress={() => router.back()}
          style={[styles.backBtn, { backgroundColor: c.surf2 }]}
        >
          <Ionicons name="arrow-back" size={18} color={c.text2} />
        </TouchableOpacity>

        <View style={styles.headerMid}>
          <Text style={[styles.headerTitle, { color: c.text }]} numberOfLines={1}>
            {session?.seniority} {session?.target_role}
          </Text>
          <Text style={[styles.headerSub, { color: c.text3 }]}>
            {new Date(session?.created_at || '').toLocaleDateString('en-IN', {
              day: 'numeric',
              month: 'short',
              year: 'numeric',
            })} · {qaPairs.length} questions
          </Text>
        </View>

        <TouchableOpacity
          onPress={() => handleDownload()}
          style={[styles.downloadBtn, {
            backgroundColor: isDark ? Colors.terra.dim : '#FBF0ED',
          }]}
        >
          <Ionicons name="share-outline" size={18} color={Colors.terra.DEFAULT} />
        </TouchableOpacity>
      </View>

      <View style={[styles.scoreSummary, {
        backgroundColor: c.surf,
        borderBottomColor: c.border,
      }]}>
        <View style={styles.scoreSummaryItem}>
          <Text style={[styles.scoreSummaryNum, { color: Colors.terra.DEFAULT }]}>
            {session?.avg_score?.toFixed(1) || '—'}
          </Text>
          <Text style={[styles.scoreSummaryLbl, { color: c.text3 }]}>avg score</Text>
        </View>

        <View style={[styles.scoreDivider, { backgroundColor: c.border }]} />

        <View style={styles.scoreSummaryItem}>
          <Text style={[styles.scoreSummaryNum, {
            color: isDark ? Colors.lavender : Colors.indigo.DEFAULT,
          }]}>
            {qaPairs.length}
          </Text>
          <Text style={[styles.scoreSummaryLbl, { color: c.text3 }]}>questions</Text>
        </View>

        <View style={[styles.scoreDivider, { backgroundColor: c.border }]} />

        <View style={styles.scoreSummaryItem}>
          <Text style={[styles.scoreSummaryNum, { color: Colors.amber.DEFAULT }]}>
            {qaPairs.filter(q => q.overall_score >= 4).length}
          </Text>
          <Text style={[styles.scoreSummaryLbl, { color: c.text3 }]}>strong</Text>
        </View>

        <View style={[styles.scoreDivider, { backgroundColor: c.border }]} />

        <View style={styles.scoreSummaryItem}>
          <Text style={[styles.scoreSummaryNum, { color: Colors.indigo.light }]}>
            {qaPairs.filter(q => q.overall_score < 3).length}
          </Text>
          <Text style={[styles.scoreSummaryLbl, { color: c.text3 }]}>weak</Text>
        </View>
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scroll}
      >
        {qaPairs.length === 0 ? (
          <View style={styles.emptyWrap}>
            <Text style={styles.emptyEmoji}>📭</Text>
            <Text style={[styles.emptyText, { color: c.text2 }]}>
              No questions found for this session.
            </Text>
          </View>
        ) : (
          qaPairs.map((qa) => {
            const isExpanded = expandedIds.has(qa.question_id);

            return (
              <View
                key={qa.question_id}
                style={[styles.qaCard, {
                  backgroundColor: c.surf,
                  borderColor: c.border,
                }]}
              >
                <TouchableOpacity
                  style={styles.qaHeader}
                  onPress={() => toggleExpand(qa.question_id)}
                  activeOpacity={0.7}
                >
                  <View style={[styles.qNumBadge, {
                    backgroundColor: isDark ? Colors.indigo.dim : '#EDE9F8',
                  }]}>
                    <Text style={[styles.qNum, {
                      color: isDark ? Colors.lavender : Colors.indigo.DEFAULT,
                    }]}>
                      Q{qa.sequence_number}
                    </Text>
                  </View>

                  <View style={styles.qMeta}>
                    <View style={styles.qTypeRow}>
                      <Ionicons
                        name={typeIcon(qa.question_type) as any}
                        size={12}
                        color={c.text3}
                      />
                      <Text style={[styles.qType, { color: c.text3 }]}>
                        {qa.question_type}
                        {qa.is_followup ? ' · follow-up' : ''}
                      </Text>
                    </View>

                    <Text
                      style={[styles.qText, { color: c.text }]}
                      numberOfLines={isExpanded ? undefined : 2}
                    >
                      {qa.question_text}
                    </Text>
                  </View>

                  <View style={styles.qRight}>
                    <Text style={[styles.qScore, { color: scoreColor(qa.overall_score) }]}>
                      {qa.overall_score?.toFixed(1) || '—'}
                    </Text>
                    <Ionicons
                      name={isExpanded ? 'chevron-up' : 'chevron-down'}
                      size={16}
                      color={c.text3}
                    />
                  </View>
                </TouchableOpacity>

                {isExpanded && (
                  <View style={[styles.qaDetail, { borderTopColor: c.border }]}>
                    <View style={styles.miniScoreRow}>
                      {Object.entries(qa.scores).map(([dim, score]) => (
                        <View key={dim} style={styles.miniScoreItem}>
                          <Text style={[styles.miniScoreLbl, { color: c.text3 }]}>
                            {dim.charAt(0).toUpperCase()}
                          </Text>

                          <View style={[styles.miniScoreBar, { backgroundColor: c.border }]}>
                            <View style={[
                              styles.miniScoreBarFill,
                              {
                                height: `${(score / 5) * 100}%`,
                                backgroundColor: scoreColor(score),
                              },
                            ]} />
                          </View>

                          <Text style={[styles.miniScoreNum, { color: scoreColor(score) }]}>
                            {score}
                          </Text>
                        </View>
                      ))}
                    </View>

                    {qa.transcript ? (
                      <View style={[styles.section, {
                        backgroundColor: isDark ? Colors.dark.surf2 : Colors.light.surf2,
                        borderRadius: 10,
                        padding: 12,
                        marginBottom: 10,
                      }]}>
                        <Text style={[styles.sectionLabel, {
                          color: isDark ? Colors.lavender : Colors.indigo.DEFAULT,
                        }]}>
                          YOUR ANSWER
                        </Text>
                        <Text style={[styles.sectionText, { color: c.text }]}>
                          {qa.transcript}
                        </Text>
                      </View>
                    ) : null}

                    {qa.strengths ? (
                      <View style={[styles.section, {
                        backgroundColor: isDark ? '#1A2820' : '#E8F5EE',
                        borderRadius: 10,
                        padding: 12,
                        marginBottom: 10,
                      }]}>
                        <Text style={[styles.sectionLabel, { color: '#2ECC9A' }]}>
                          ✓ STRENGTHS
                        </Text>
                        <Text style={[styles.sectionText, {
                          color: isDark ? '#A8E6CF' : '#1A5C40',
                        }]}>
                          {qa.strengths}
                        </Text>
                      </View>
                    ) : null}

                    {qa.gaps ? (
                      <View style={[styles.section, {
                        backgroundColor: isDark ? Colors.terra.dim : '#FBF0ED',
                        borderRadius: 10,
                        padding: 12,
                        marginBottom: 10,
                      }]}>
                        <Text style={[styles.sectionLabel, { color: Colors.terra.DEFAULT }]}>
                          ⚠ GAPS
                        </Text>
                        <Text style={[styles.sectionText, {
                          color: isDark ? Colors.terra.light : '#7A3020',
                        }]}>
                          {qa.gaps}
                        </Text>
                      </View>
                    ) : null}

                    {qa.coaching_tip ? (
                      <View style={[styles.section, {
                        backgroundColor: isDark ? Colors.amber.dim : '#FEF9EC',
                        borderRadius: 10,
                        padding: 12,
                        marginBottom: 10,
                      }]}>
                        <Text style={[styles.sectionLabel, { color: Colors.amber.DEFAULT }]}>
                          💡 COACHING TIP
                        </Text>
                        <Text style={[styles.sectionText, {
                          color: isDark ? '#D4A850' : '#6B5010',
                        }]}>
                          {qa.coaching_tip}
                        </Text>
                      </View>
                    ) : null}

                    {qa.ideal_answer ? (
                      <View style={[styles.section, {
                        backgroundColor: isDark ? Colors.indigo.dim : '#EDE9F8',
                        borderRadius: 10,
                        padding: 12,
                        marginBottom: 4,
                      }]}>
                        <Text style={[styles.sectionLabel, {
                          color: isDark ? Colors.lavender : Colors.indigo.DEFAULT,
                        }]}>
                          ✦ IDEAL ANSWER
                        </Text>
                        <Text style={[styles.sectionText, {
                          color: isDark ? '#C0BFFF' : '#2A2050',
                        }]}>
                          {qa.ideal_answer}
                        </Text>
                      </View>
                    ) : null}
                  </View>
                )}
              </View>
            );
          })
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16 },
  loadingText: { fontSize: 14 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
    borderBottomWidth: 1,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerMid: { flex: 1 },
  headerTitle: { fontSize: 16, fontWeight: '700' },
  headerSub: { fontSize: 11, marginTop: 2 },
  downloadBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scoreSummary: {
    flexDirection: 'row',
    padding: 14,
    borderBottomWidth: 1,
  },
  scoreSummaryItem: { flex: 1, alignItems: 'center' },
  scoreSummaryNum: { fontSize: 20, fontWeight: '700' },
  scoreSummaryLbl: { fontSize: 10, marginTop: 2 },
  scoreDivider: { width: 1, marginVertical: 4 },
  scroll: { padding: 16, paddingBottom: 48 },
  emptyWrap: { alignItems: 'center', padding: 48, gap: 12 },
  emptyEmoji: { fontSize: 40 },
  emptyText: { fontSize: 14, textAlign: 'center' },
  qaCard: {
    borderRadius: 14,
    borderWidth: 1,
    marginBottom: 12,
    overflow: 'hidden',
  },
  qaHeader: {
    flexDirection: 'row',
    padding: 14,
    gap: 10,
    alignItems: 'flex-start',
  },
  qNumBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  qNum: { fontSize: 12, fontWeight: '700' },
  qMeta: { flex: 1 },
  qTypeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 4,
  },
  qType: {
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  qText: { fontSize: 14, lineHeight: 20, fontWeight: '500' },
  qRight: { alignItems: 'flex-end', gap: 4, flexShrink: 0 },
  qScore: { fontSize: 18, fontWeight: '700' },
  qaDetail: { borderTopWidth: 1, padding: 12, gap: 0 },
  miniScoreRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 14,
    paddingVertical: 8,
  },
  miniScoreItem: { alignItems: 'center', gap: 4 },
  miniScoreLbl: { fontSize: 10, fontWeight: '600' },
  miniScoreBar: {
    width: 6,
    height: 40,
    borderRadius: 3,
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  miniScoreBarFill: { width: '100%', borderRadius: 3 },
  miniScoreNum: { fontSize: 10, fontWeight: '700' },
  section: { marginBottom: 0 },
  sectionLabel: {
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.6,
    marginBottom: 6,
  },
  sectionText: { fontSize: 13, lineHeight: 20 },
});